force-app/main/default/objects/Project__c/Project__c.object-meta.xml
<CustomObject>
    <label>Project</label>
    <nameField>
        <label>Project Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Projects</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Project__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>IN DEVELOPMENT</fullName>
            </value>
            <value>
                <fullName>PUBLISHED</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Project__c/fields/Version__c.field-meta.xml
<CustomField>
    <fullName>Version__c</fullName>
    <label>Version</label>
    <precision>5</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/UseCase__c/UseCase__c.object-meta.xml
<CustomObject>
    <label>UseCase</label>
    <nameField>
        <label>UseCase Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>UseCases</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/UseCase__c/fields/Number__c.field-meta.xml
<CustomField>
    <fullName>Number__c</fullName>
    <label>UseCase Number</label>
    <precision>18</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/UseCase__c/fields/Priority__c.field-meta.xml
<CustomField>
    <fullName>Priority__c</fullName>
    <label>Priority</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Priority</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/UseCase__c/fields/Project__c.field-meta.xml
<CustomField>
    <fullName>Project__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Project</label>
    <referenceTo>Project__c</referenceTo>
    <relationshipLabel>UseCases</relationshipLabel>
    <relationshipName>UseCases</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/UseCase__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>IN_DEVELOPMENT</fullName>
            </value>
            <value>
                <fullName>PUBLISHED</fullName>
            </value>
            <value>
                <fullName>DELETED</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/command/domain/factory/UseCaseFactory.cls
public with sharing class UseCaseFactory {

    private static final Integer FIRST_VERSION = 1;
    
    private final UseCaseRepository useCaseRepository;
    private final ProjectRepository projectRepository;

    public UseCaseFactory( final UseCaseRepository useCaseRepository
                         , final ProjectRepository projectRepository ){
        this.useCaseRepository = useCaseRepository;
        this.projectRepository = projectRepository;
    }

    public UseCase constructNew( final UseCaseCommandDto useCaseCommandDto ){

        return new UseCase( null
                          , useCaseCommandDto.name
                          , useCaseCommandDto.useCaseNumber
                          , null
                          , UseCaseStatus.IN_DEVELOPMENT
                          , FIRST_VERSION
                          , PriorityUtils.valueOf( useCaseCommandDto.priority )
                          , constructProjectOfUseCase( useCaseCommandDto.projectId ) );
    }

    public void create( final UseCase useCase ){
        useCaseRepository.create( toUseCaseRepoDto( useCase ) );
    }


    ///////////////////
    /// Utils
    ///////////////////

    private ProjectOfUseCase constructProjectOfUseCase( final String projectId ) {

        final Project__c projectRepoDto = projectRepository.fetchById( projectId );

        return new ProjectOfUseCase( projectRepoDto.Id
                                   , projectRepoDto.Name
                                   , projectRepoDto.Description__c
                                   , ProjectStatusUtils.valueOf( projectRepoDto.Status__c )
                                   , projectRepoDto.Version__c.intValue()
                                   , PriorityUtils.valueOf( projectRepoDto.Priority__c ) );
    }

    private UseCase__c toUseCaseRepoDto( final UseCase useCase ){

        return new UseCase__c( Name = useCase.getName()
                             , Number__c = useCase.getUseCaseNumber()
                             , Description__c = useCase.getDescription()
                             , Status__c = useCase.getStatus().name()
                             , Version__c = useCase.getVersion()
                             , Priority__c= useCase.getPriority().name()
                             , Project__c = useCase.getProjectOfUseCase().getId() );
    }

}