force-app/main/default/objects/Project__c/Project__c.object-meta.xml
<CustomObject>
    <label>Project</label>
    <nameField>
        <label>Project Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Projects</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Project__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>IN DEVELOPMENT</fullName>
            </value>
            <value>
                <fullName>PUBLISHED</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Project__c/fields/Version__c.field-meta.xml
<CustomField>
    <fullName>Version__c</fullName>
    <label>Version</label>
    <precision>5</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/UseCase__c/UseCase__c.object-meta.xml
<CustomObject>
    <label>UseCase</label>
    <nameField>
        <label>UseCase Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>UseCases</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/UseCase__c/fields/Number__c.field-meta.xml
<CustomField>
    <fullName>Number__c</fullName>
    <label>UseCase Number</label>
    <precision>18</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/UseCase__c/fields/Priority__c.field-meta.xml
<CustomField>
    <fullName>Priority__c</fullName>
    <label>Priority</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Priority</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/UseCase__c/fields/Project__c.field-meta.xml
<CustomField>
    <fullName>Project__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Project</label>
    <referenceTo>Project__c</referenceTo>
    <relationshipLabel>UseCases</relationshipLabel>
    <relationshipName>UseCases</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/UseCase__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>IN_DEVELOPMENT</fullName>
            </value>
            <value>
                <fullName>PUBLISHED</fullName>
            </value>
            <value>
                <fullName>DELETED</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/repository/UseCaseRepository.cls
public with sharing class UseCaseRepository {
    
    public List<UseCase__c> fetchListByProjectIds( final List<String> projectIds ){
        return [ SELECT Id, Name, Number__c, Description__c, Status__c, Version__c, Priority__c, Project__r.Id
                 FROM UseCase__c
                 WHERE Project__r.Id IN :projectIds AND Status__c != 'DELETED'
                 LIMIT 50000 ];
    }

    public UseCase__c fetchById( final String useCaseId ){
        return [ SELECT Id, Name, Number__c, Description__c, Status__c, Version__c, Priority__c, Project__r.Id
                 FROM UseCase__c
                 WHERE Id=:useCaseId
                 LIMIT 1 ];
    }

    public void creating( final UseCase__c useCaseRepoDto ) {
        insert useCaseRepoDto;
    }
}