force-app/main/default/objects/Project__c/Project__c.object-meta.xml
<CustomObject>
    <label>Project</label>
    <nameField>
        <label>Project Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Projects</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Project__c/fields/Author__c.field-meta.xml
<CustomField>
    <fullName>Author__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Author</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Projects</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Project__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>IN DEVELOPMENT</fullName>
            </value>
            <value>
                <fullName>PUBLISHED</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Project__c/fields/Version__c.field-meta.xml
<CustomField>
    <fullName>Version__c</fullName>
    <label>Version</label>
    <precision>5</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/command/domain/factory/ProjectFactory.cls
public with sharing class ProjectFactory {
    
    private static final Integer FIRST_VERSION = 1;

    private final ProjectRepository projectRepository;
    private final UserRepository userRepository;

    public ProjectFactory( final ProjectRepository projectRepository
                         , final UserRepository userRepository ) {
        this.projectRepository = projectRepository;
        this.userRepository = userRepository;                    
    }

    public Project constructNew( final ProjectCommandDto projectCommandDto ) {
        return new Project( null
                          , projectCommandDto.name
                          , projectCommandDto.description
                          , ProjectStatus.IN_DEVELOPMENT
                          , FIRST_VERSION
                          , Priority.valueOf( projectCommandDto.priority ) 
                          , constructAuthor()
                          );
    }

    public void create( final Project project ){
        projectRepository.create( toProjectRepoDto( project ) );
    }


    ///////////////////
    /// Utils
    ///////////////////

    private UserInformation constructAuthor() {

        final User authorRepoDto = userRepository.fetchBy( UserInfo.getUserId() );
        return new UserInformation( authorRepoDto.id, authorRepoDto.name );

    }

    private Project__c toProjectRepoDto( final Project project ){
        return new Project__c( Name = project.getName()
                             , Description__c = project.getDescription()
                             , Status__c = project.getStatus().name()
                             , Version__c = project.getVersion()
                             , Priority__c = project.getPriority().name()
                             , Author__c = project.getAuthor().getId() );
    }
}