force-app/main/default/objects/Project__c/Project__c.object-meta.xml
<CustomObject>
    <label>Project</label>
    <nameField>
        <label>Project Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Projects</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Project__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>IN DEVELOPMENT</fullName>
            </value>
            <value>
                <fullName>PUBLISHED</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Project__c/fields/Version__c.field-meta.xml
<CustomField>
    <fullName>Version__c</fullName>
    <label>Version</label>
    <precision>5</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/UseCase__c/UseCase__c.object-meta.xml
<CustomObject>
    <label>UseCase</label>
    <nameField>
        <label>UseCase Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>UseCases</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/UseCase__c/fields/Number__c.field-meta.xml
<CustomField>
    <fullName>Number__c</fullName>
    <label>UseCase Number</label>
    <precision>18</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/UseCase__c/fields/Priority__c.field-meta.xml
<CustomField>
    <fullName>Priority__c</fullName>
    <label>Priority</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Priority</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/UseCase__c/fields/Project__c.field-meta.xml
<CustomField>
    <fullName>Project__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Project</label>
    <referenceTo>Project__c</referenceTo>
    <relationshipLabel>UseCases</relationshipLabel>
    <relationshipName>UseCases</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/UseCase__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>IN_DEVELOPMENT</fullName>
            </value>
            <value>
                <fullName>PUBLISHED</fullName>
            </value>
            <value>
                <fullName>DELETED</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/query/service/UseCaseQueryService.cls
public with sharing class UseCaseQueryService {

    private UseCaseRepository useCaseRepository;

    public UseCaseQueryService( final UseCaseRepository useCaseRepository ) {
        this.useCaseRepository = useCaseRepository;
    }

    public List<UseCaseQueryDto> fetchListByProjectIds( final List<String> projectIds ){
        
        final List<UseCase__c> useCaseRepoDtos = useCaseRepository.fetchListByProjectIds( projectIds );

        final List<UseCaseQueryDto> resultList = new List<UseCaseQueryDto>();

        for( UseCase__c useCaseRepoDto : useCaseRepoDtos ){
            resultList.add( toUseCaseQueryDto( useCaseRepoDto ) );
        }
        
        return resultList;
    }


    ///////////////////
    /// Utils 
    //////////////////

    private UseCaseQueryDto toUseCaseQueryDto( final UseCase__c useCase ){
        return new UseCaseQueryDto( useCase.ID
                                  , useCase.Name
                                  , useCase.Number__c.intValue()
                                  , useCase.Description__c
                                  , useCase.Status__c
                                  , useCase.Version__c.intValue()
                                  , useCase.Priority__c
                                  , useCase.Project__r.Id );
    }
}