force-app/main/default/objects/Project__c/Project__c.object-meta.xml
<CustomObject>
    <label>Project</label>
    <nameField>
        <label>Project Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Projects</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Project__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>IN DEVELOPMENT</fullName>
            </value>
            <value>
                <fullName>PUBLISHED</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Project__c/fields/Version__c.field-meta.xml
<CustomField>
    <fullName>Version__c</fullName>
    <label>Version</label>
    <precision>5</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/query/service/FlatProjectQueryService.cls
public with sharing class FlatProjectQueryService {

    private final ProjectRepository projectRepository;

    public FlatProjectQueryService( final ProjectRepository projectRepository ) {
        this.projectRepository = projectRepository;
    }

    public List<FlatProjectQueryDto> fetchAll(){
        
        final List<Project__c> projectRepoDtos = projectRepository.fetchAll();

        final List<FlatProjectQueryDto> resultList = new List<FlatProjectQueryDto>();

        for( Project__c projectRepoDto : projectRepoDtos ){
            resultList.add( toFlatProjectQueryDto( projectRepoDto ) );
        }

        return resultList;
    }

    public FlatProjectQueryDto fetchBy( final String projectId ){

        final Project__c projectRepoDto = projectRepository.fetchById( projectId );

        return toFlatProjectQueryDto( projectRepoDto );
    }


    ///////////////
    /// Utils
    ///////////////

    private FlatProjectQueryDto toFlatProjectQueryDto( final Project__c projectRepoDto ) {
        return new FlatProjectQueryDto( projectRepoDto.Id
                                      , projectRepoDto.Name
                                      , projectRepoDto.Description__c
                                      , projectRepoDto.Status__c
                                      , projectRepoDto.Version__c.intValue()
                                      , projectRepoDto.Priority__c );
    }
}