force-app/main/default/objects/Project__c/Project__c.object-meta.xml
<CustomObject>
    <label>Project</label>
    <nameField>
        <label>Project Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Projects</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Project__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>IN DEVELOPMENT</fullName>
            </value>
            <value>
                <fullName>PUBLISHED</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Project__c/fields/Version__c.field-meta.xml
<CustomField>
    <fullName>Version__c</fullName>
    <label>Version</label>
    <precision>5</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/repository/ProjectRepository.cls
public with sharing class ProjectRepository {
    
    public List<Project__c> fetchAll() {
        return [ SELECT Id, Name, Description__c, Status__c, Version__c, Priority__c
                 FROM Project__c
                 WHERE Status__c != 'DELETED'
                 LIMIT 50000 ];
    }

    public Project__c fetchById( final String id ) {
        return [ SELECT Id, Name, Description__c, Status__c, Version__c, Priority__c
                 FROM Project__c
                 WHERE Id=: id
                 LIMIT 1];
    }

    public void creating( final Project__c projectRepoDto ) {
        insert projectRepoDto;
    }

    public void updating( final Project__c projectRepoDto ) {
        update projectRepoDto;
    }
}